version: '3.8'
services:
  ms-sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Pa55w0rd2022"
    ports:
      - "1433:1433"
  social-app:
    build: .
    environment:
        DBServer: "ms-sql-server"
        DBUser: "SA"
        DBPassword: "Pa55w0rd2022"
    ports:
      - "8080:80"